-- Create public.ok table for storing challenge results per round
create table if not exists public.ok (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Username" text,
  "Mailadresse" text,
  "Rundenr" text,
  "Punkte" text
);

-- Enable Row Level Security and allow public read/insert (no auth required)
alter table public.ok enable row level security;

create policy "Public can insert into ok"
  on public.ok
  for insert
  to anon, authenticated
  with check (true);

create policy "Public can select from ok"
  on public.ok
  for select
  to anon, authenticated
  using (true);
