-- Fix auto-increment for id columns in tables
-- This will allow inserts to work properly by automatically generating IDs

-- Update the 'ok' table to have auto-incrementing id
ALTER TABLE public.ok ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Update the 'Name' table to have auto-incrementing id  
ALTER TABLE public."Name" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Ensure both tables have proper primary key constraints
ALTER TABLE public.ok ADD CONSTRAINT IF NOT EXISTS ok_pkey PRIMARY KEY (id);
ALTER TABLE public."Name" ADD CONSTRAINT IF NOT EXISTS name_pkey PRIMARY KEY (id);